train:
  mode: run_svm
model:
  svm_cost: 0.5
  svm_gamma: 0.1
  svm_class_weights: 3
dataset:
  graph_interpretation: bipartite_projection
  format: SBML_multi
  train_names: [AlzPathwayReorg]
  test_names: [PDMap]
  split: [1.0,0.0]
  feat_cache: "enabled"
  augment_feature:
    - "node_degree"
    - "node_degree_projection"
    - "node_clustering_coefficient"
    - "node_betweenness_centrality"
    - "node_betweenness_centrality_projection"
    - "node_closeness_centrality"
    - "node_closeness_centrality_projection"
    - "node_eigenvector_centrality"
    - "node_eigenvector_centrality_projection"
    - "node_neighbour_centrality_statistics"
    - "node_neighbour_centrality_statistics_projection"
    - "node_distance_set_size"
    - "node_distance_set_size_projection"
    - "node_class_onehot"
#    - "node_ego_centralities"
#    - "node_ego_centralities_projection"
  transform: normalize
  # must appear above
  # normalize_feats specified by default value if not given
  augment_feature_dims: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
  augment_feature_repr: original
  augment_label: ''
  augment_label_dims: 0
  task: node
  task_type: classification
  transductive: True