train:
  mode: run_svm
dataset:
  format: SBML_multi
  train_names: [AlzPathway,PDMap]
  test_names: [ReconMapOlder]
  split: [0.99,0.01]  # internal split
  exclude_complex_species: True
  feat_cache: "enabled"
  augment_feature:
    - "node_degree"
    - "node_degree_projection"
    - "node_clustering_coefficient"
    - "node_betweenness_centrality"
    - "node_betweenness_centrality_projection"
    - "node_closeness_centrality"
    - "node_closeness_centrality_projection"
    - "node_eigenvector_centrality"
    - "node_eigenvector_centrality_projection"
    - "node_neighbour_centrality_statistics"
    - "node_neighbour_centrality_statistics_projection"
    - "node_distance_set_size"
    - "node_distance_set_size_projection"
    - "node_class_onehot"
  #    - "node_ego_centralities"
  #    - "node_ego_centralities_projection"
  transform: normalize
  augment_feature_dims: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
  augment_feature_repr: original
  augment_label: ''
  augment_label_dims: 0
  task: node
  task_type: classification
  transductive: True